# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024 Stefan Lengfeld <stefan@lengfeld.xyz>

all:
	@echo Nothing to do yet

.PHONY: tests
tests:
	python3 -m unittest parse_html parse_table_data diff_file_infos dump_file_infos_test watcher
